import Todo from "../components/toDo"

export const metadata = {
    title: 'Posts Next App',
    description: 'Generated by create next app',
}

export default async function posts() {

    const response = await fetch('https://jsonplaceholder.typicode.com/todos/1'
        // {
        //     cache: 'no-store', // SSG
        //     cache: 'force-cache'// SSR
        // },
        // next = {
        //     revalidate: 60, // ISG
        // }
    )
    const toDo = await response.json()

    return (
        <div className="flex flex-col justify-center items-center h-screen text-3xl">
            <h1>posts</h1>
            <h1>{toDo.title}</h1>
            <h2>
                <Todo />
            </h2>
        </div>
    )
}