export const metadata = {
    title: ' Article Next App',
    description: 'Generated by create next app',
}
const layout = ({ children }) => {
    return (
        <>
            {/* <div>layout</div> */}
            <div className="flex flex-col items-center justify-center p-5 bg-blue-900 rounded-md mt-20">{children}</div>
        </>

    )
}

export default layout